// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: xx75S8QvJWRspcqMPvFTwe
// Component: Mk9MEh4U4v
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: xx75S8QvJWRspcqMPvFTwe/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: Mk9MEh4U4v/css

import GroupIcon from "./icons/PlasmicIcon__Group"; // plasmic-import: wNYZdzCAE/icon
import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: 0HxfaBY5dj/icon
import Ellipse3Icon from "./icons/PlasmicIcon__Ellipse3"; // plasmic-import: e4uSmmYO2zN/icon
import Vector2Icon from "./icons/PlasmicIcon__Vector2"; // plasmic-import: kgfngmNuhY5/icon
import Vector3Icon from "./icons/PlasmicIcon__Vector3"; // plasmic-import: ucjbnhycQno/icon
import Group3Icon from "./icons/PlasmicIcon__Group3"; // plasmic-import: 7S6doOpA7X6/icon
import Line1Icon from "./icons/PlasmicIcon__Line1"; // plasmic-import: tysHezriu11/icon
import Line3Icon from "./icons/PlasmicIcon__Line3"; // plasmic-import: izoSlNZZtwX/icon
import Group4Icon from "./icons/PlasmicIcon__Group4"; // plasmic-import: n9E9IbwoZZO/icon
import Vector4Icon from "./icons/PlasmicIcon__Vector4"; // plasmic-import: LTmemUvPctH/icon
import Line4Icon from "./icons/PlasmicIcon__Line4"; // plasmic-import: yWA15Xrp0NW/icon
import Group6Icon from "./icons/PlasmicIcon__Group6"; // plasmic-import: 9RfeKRy6hDA/icon
import Vector5Icon from "./icons/PlasmicIcon__Vector5"; // plasmic-import: NCQ2saPw4k3/icon

export type PlasmicHomepage__VariantMembers = {};

export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: p.Flex<"div">;
  figmaPaste?: p.Flex<"div">;
  gmZillaLandingPage?: p.Flex<"div">;
  sunny1?: p.Flex<"div">;
  rectangle11?: p.Flex<"div">;
  rectangle16?: p.Flex<"div">;
  rectangle1?: p.Flex<"div">;
  frame?: p.Flex<"div">;
  group?: p.Flex<"div">;
  layer1?: p.Flex<"div">;
  group2?: p.Flex<"div">;
  rectangle3?: p.Flex<"div">;
  rectangle5?: p.Flex<"div">;
  rectangle13?: p.Flex<"div">;
  cherryBlossom2021?: p.Flex<"div">;
  rectangle6?: p.Flex<"div">;
  group3?: p.Flex<"div">;
  rectangle2?: p.Flex<"div">;
  group4?: p.Flex<"div">;
  group1?: p.Flex<"div">;
  preview11?: p.Flex<"div">;
  rectangle4?: p.Flex<"div">;
  rectangle7?: p.Flex<"div">;
  group7?: p.Flex<"div">;
  image4?: p.Flex<"div">;
  rectangle8?: p.Flex<"div">;
  group6?: p.Flex<"div">;
  image3?: p.Flex<"div">;
  rectangle9?: p.Flex<"div">;
  group5?: p.Flex<"div">;
  image1?: p.Flex<"div">;
  rectangle10?: p.Flex<"div">;
  group8?: p.Flex<"div">;
  image2?: p.Flex<"div">;
  rectangle12?: p.Flex<"div">;
  rectangle14?: p.Flex<"div">;
  group13?: p.Flex<"div">;
  group14?: p.Flex<"div">;
  _6011?: p.Flex<"div">;
  group16?: p.Flex<"div">;
  group17?: p.Flex<"div">;
  group18?: p.Flex<"div">;
  group19?: p.Flex<"div">;
  group15?: p.Flex<"div">;
  gmztaPreview1?: p.Flex<"div">;
  group9?: p.Flex<"div">;
  layer2?: p.Flex<"div">;
  group10?: p.Flex<"div">;
  rectangle15?: p.Flex<"div">;
  rectangle17?: p.Flex<"div">;
  setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats?: p.Flex<"div">;
  rectangle18?: p.Flex<"div">;
  rectangle19?: p.Flex<"div">;
  rectangle20?: p.Flex<"div">;
  rectangle21?: p.Flex<"div">;
  group20?: p.Flex<"div">;
  group21?: p.Flex<"div">;
  group11?: p.Flex<"div">;
  layer3?: p.Flex<"div">;
  group12?: p.Flex<"div">;
  group27?: p.Flex<"div">;
  group22?: p.Flex<"div">;
  image5?: p.Flex<"div">;
  rectangle22?: p.Flex<"div">;
  group26?: p.Flex<"div">;
  group23?: p.Flex<"div">;
  image6?: p.Flex<"div">;
  rectangle23?: p.Flex<"div">;
  group25?: p.Flex<"div">;
  group24?: p.Flex<"div">;
  image7?: p.Flex<"div">;
  rectangle24?: p.Flex<"div">;
  rectangle25?: p.Flex<"div">;
  rectangle26?: p.Flex<"div">;
};

export interface DefaultHomepageProps {
  dataFetches: PlasmicHomepage__Fetches;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  dataFetches?: PlasmicHomepage__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            defaultcss.all,
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"figmaPaste"}
            data-plasmic-override={overrides.figmaPaste}
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.figmaPaste
            )}
          >
            <div
              data-plasmic-name={"gmZillaLandingPage"}
              data-plasmic-override={overrides.gmZillaLandingPage}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.gmZillaLandingPage
              )}
            >
              <div
                data-plasmic-name={"sunny1"}
                data-plasmic-override={overrides.sunny1}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.sunny1
                )}
              />

              <div
                data-plasmic-name={"rectangle11"}
                data-plasmic-override={overrides.rectangle11}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.rectangle11
                )}
              />

              <div
                data-plasmic-name={"rectangle16"}
                data-plasmic-override={overrides.rectangle16}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.rectangle16
                )}
              />

              <div
                data-plasmic-name={"rectangle1"}
                data-plasmic-override={overrides.rectangle1}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.rectangle1
                )}
              />

              <div
                data-plasmic-name={"frame"}
                data-plasmic-override={overrides.frame}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.frame
                )}
              >
                <div
                  data-plasmic-name={"group"}
                  data-plasmic-override={overrides.group}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.group
                  )}
                >
                  <div
                    data-plasmic-name={"layer1"}
                    data-plasmic-override={overrides.layer1}
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.layer1
                    )}
                  >
                    <GroupIcon
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.svg__vnP9F
                      )}
                      role={"img"}
                    />

                    <div
                      data-plasmic-name={"group2"}
                      data-plasmic-override={overrides.group2}
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.group2
                      )}
                    >
                      <VectorIcon
                        className={classNames(
                          defaultcss.all,
                          projectcss.all,
                          sty.svg__sovke
                        )}
                        role={"img"}
                      />

                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__kZnfr)}
                        displayHeight={"144.263px" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"143.23px" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/blank_project/images/group2.svg",
                          fullWidth: 143.23,
                          fullHeight: 144.263,
                          aspectRatio: 0.993103
                        }}
                      />
                    </div>
                  </div>
                </div>
              </div>

              <div
                data-plasmic-name={"rectangle3"}
                data-plasmic-override={overrides.rectangle3}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.rectangle3
                )}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__gb1Yr
                )}
              >
                {"Coming Soon..."}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__lZp
                )}
              >
                {"10,000 of 10,000 available"}
              </div>

              <div
                data-plasmic-name={"rectangle5"}
                data-plasmic-override={overrides.rectangle5}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.rectangle5
                )}
              />

              <div
                data-plasmic-name={"rectangle13"}
                data-plasmic-override={overrides.rectangle13}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.rectangle13
                )}
              />

              <div
                data-plasmic-name={"cherryBlossom2021"}
                data-plasmic-override={overrides.cherryBlossom2021}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.cherryBlossom2021
                )}
              />

              <div
                data-plasmic-name={"rectangle6"}
                data-plasmic-override={overrides.rectangle6}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.rectangle6
                )}
              />

              <div
                data-plasmic-name={"group3"}
                data-plasmic-override={overrides.group3}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.group3
                )}
              >
                <div
                  data-plasmic-name={"rectangle2"}
                  data-plasmic-override={overrides.rectangle2}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.rectangle2
                  )}
                />

                <div
                  data-plasmic-name={"group4"}
                  data-plasmic-override={overrides.group4}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.group4
                  )}
                >
                  <div
                    data-plasmic-name={"group1"}
                    data-plasmic-override={overrides.group1}
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.group1
                    )}
                  >
                    <div
                      data-plasmic-name={"preview11"}
                      data-plasmic-override={overrides.preview11}
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.preview11
                      )}
                    />
                  </div>

                  <Ellipse3Icon
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.svg___20Zgc
                    )}
                    role={"img"}
                  />
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__eb90J
                  )}
                >
                  {"GET YOUR"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__ciRdZ
                  )}
                >
                  {"GMZillas"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__mlGb
                  )}
                >
                  {
                    "GMZTA is a collection of 10,000 unique generated NFTs (0.05 ETH) launching in December on Ethereum Mainnet.\n\nOur Roadmap 1.0 consists of explosive utilities for GMZTA holders that will elevate your NFT experience and give every Genesis GMZilla holders exclusive access for future drops in our roadmap."
                  }
                </div>

                <div
                  data-plasmic-name={"rectangle4"}
                  data-plasmic-override={overrides.rectangle4}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.rectangle4
                  )}
                />

                <div
                  data-plasmic-name={"rectangle7"}
                  data-plasmic-override={overrides.rectangle7}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.rectangle7
                  )}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__lr42U
                  )}
                >
                  {"Coming Soon..."}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__dtuPf
                  )}
                >
                  {"10,000 of 10,000 available"}
                </div>
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__tS5Oh
                )}
              >
                {"OUR TEAM"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text___8Iz4M
                )}
              >
                {"ROADMAP 1.0"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__evcMp
                )}
              >
                {"MomoJira"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__c3U
                )}
              >
                {"Project Manager"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__aqqq1
                )}
              >
                {"Gojiberri"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text___7RoCb
                )}
              >
                {"Marketing Lead"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__eQCh
                )}
              >
                {"GM Jira"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__yRj8N
                )}
              >
                {"Business Developer"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__r7S3U
                )}
              >
                {"Macjira"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__hkQb5
                )}
              >
                {"Full-stack Developer"}
              </div>

              <div
                data-plasmic-name={"group7"}
                data-plasmic-override={overrides.group7}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.group7
                )}
              >
                <div
                  data-plasmic-name={"image4"}
                  data-plasmic-override={overrides.image4}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.image4
                  )}
                />
              </div>

              <div
                data-plasmic-name={"rectangle8"}
                data-plasmic-override={overrides.rectangle8}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.rectangle8
                )}
              />

              <div
                data-plasmic-name={"group6"}
                data-plasmic-override={overrides.group6}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.group6
                )}
              >
                <div
                  data-plasmic-name={"image3"}
                  data-plasmic-override={overrides.image3}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.image3
                  )}
                />
              </div>

              <div
                data-plasmic-name={"rectangle9"}
                data-plasmic-override={overrides.rectangle9}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.rectangle9
                )}
              />

              <div
                data-plasmic-name={"group5"}
                data-plasmic-override={overrides.group5}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.group5
                )}
              >
                <div
                  data-plasmic-name={"image1"}
                  data-plasmic-override={overrides.image1}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.image1
                  )}
                />
              </div>

              <div
                data-plasmic-name={"rectangle10"}
                data-plasmic-override={overrides.rectangle10}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.rectangle10
                )}
              />

              <div
                data-plasmic-name={"group8"}
                data-plasmic-override={overrides.group8}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.group8
                )}
              >
                <div
                  data-plasmic-name={"image2"}
                  data-plasmic-override={overrides.image2}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.image2
                  )}
                />
              </div>

              <div
                data-plasmic-name={"rectangle12"}
                data-plasmic-override={overrides.rectangle12}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.rectangle12
                )}
              />

              <div
                data-plasmic-name={"rectangle14"}
                data-plasmic-override={overrides.rectangle14}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.rectangle14
                )}
              />

              <div
                data-plasmic-name={"group13"}
                data-plasmic-override={overrides.group13}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.group13
                )}
              >
                <div
                  data-plasmic-name={"group14"}
                  data-plasmic-override={overrides.group14}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.group14
                  )}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__qOxit
                    )}
                  >
                    {"MINT"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__b62P0
                    )}
                  >
                    {"ROADMAP"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text___0V2CU
                    )}
                  >
                    {"RANKING"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__uFnuq
                    )}
                  >
                    {"FAQ"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__ptqG9
                    )}
                  >
                    {"TEAM"}
                  </div>
                </div>
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__ouyZm
                )}
              >
                {"CONNECT"}
              </div>

              <Vector2Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__ivzZw
                )}
                role={"img"}
              />

              <Vector3Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__kobqp
                )}
                role={"img"}
              />

              <div
                data-plasmic-name={"_6011"}
                data-plasmic-override={overrides._6011}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty._6011
                )}
              />

              <Group3Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__zApQp
                )}
                role={"img"}
              />

              <div
                data-plasmic-name={"group16"}
                data-plasmic-override={overrides.group16}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.group16
                )}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__ghVfp
                  )}
                >
                  {"PHASE 1"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__ox8J
                  )}
                >
                  {
                    "- Presale spots for 500 OG Members\n- Contests and Giveaways (Additional 500 presale slots)\n- Auction of 10 Legendary GMZilla NFTs\n- Launch in December 2021 (Tentatively)"
                  }
                </div>
              </div>

              <div
                data-plasmic-name={"group17"}
                data-plasmic-override={overrides.group17}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.group17
                )}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__bUclj
                  )}
                >
                  {"PHASE 2"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__mbq0V
                  )}
                >
                  {
                    "- Rarity Sniper Rankings\n- Listed on Rarity Tools \n- GMZTA Limited Merch\n- Super Ultra Secret Project"
                  }
                </div>
              </div>

              <div
                data-plasmic-name={"group18"}
                data-plasmic-override={overrides.group18}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.group18
                )}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__dwH9N
                  )}
                >
                  {"PHASE 3"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__ri3Px
                  )}
                >
                  {
                    "- Aquire CryptoVoxel land for Community Activities\n- Proceeds of Legendary GMZilla Auction will bootstrap \n  $GTA token, and holders of every GMZTA NFT will \n  receive an airdrop, Tokenomics TBC\n- Sneak Peeks Into Super Ultra Secret Project"
                  }
                </div>
              </div>

              <div
                data-plasmic-name={"group19"}
                data-plasmic-override={overrides.group19}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.group19
                )}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text___7Ko
                  )}
                >
                  {"PHASE 4"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__ly65S
                  )}
                >
                  {
                    "- 1000 Travel Tickets to be minted using $GTA\n- Aquire Sandbox Land for development\n- Hire voxel architect to build GMZilla VX Collection"
                  }
                </div>
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text___60Vjb
                )}
              >
                {"AND MORE..."}
              </div>

              <div
                data-plasmic-name={"group15"}
                data-plasmic-override={overrides.group15}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.group15
                )}
              >
                <div
                  data-plasmic-name={"gmztaPreview1"}
                  data-plasmic-override={overrides.gmztaPreview1}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.gmztaPreview1
                  )}
                />

                <Line1Icon
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.svg__ucVhI
                  )}
                  role={"img"}
                />

                <Line1Icon
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.svg__lAghe
                  )}
                  role={"img"}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__wtX0Q
                  )}
                >
                  {"GIF"}
                </div>
              </div>

              <Line3Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__zvghc
                )}
                role={"img"}
              />

              <div
                data-plasmic-name={"group9"}
                data-plasmic-override={overrides.group9}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.group9
                )}
              >
                <div
                  data-plasmic-name={"layer2"}
                  data-plasmic-override={overrides.layer2}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.layer2
                  )}
                >
                  <Group4Icon
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.svg___99Lxp
                    )}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={"group10"}
                    data-plasmic-override={overrides.group10}
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.group10
                    )}
                  >
                    <Vector4Icon
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.svg__nM8Rd
                      )}
                      role={"img"}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__ss9AM)}
                      displayHeight={"36.474px" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"36.213px" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/blank_project/images/group5.svg",
                        fullWidth: 36.213,
                        fullHeight: 36.474,
                        aspectRatio: 1
                      }}
                    />
                  </div>
                </div>
              </div>

              <div
                data-plasmic-name={"rectangle15"}
                data-plasmic-override={overrides.rectangle15}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.rectangle15
                )}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__e32Z0
                )}
              >
                {"FAQ"}
              </div>

              <div
                data-plasmic-name={"rectangle17"}
                data-plasmic-override={overrides.rectangle17}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.rectangle17
                )}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__p0VWh
                )}
              >
                {"Ser How?"}
              </div>

              <div
                data-plasmic-name={
                  "setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats"
                }
                data-plasmic-override={
                  overrides.setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats
                }
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats
                )}
              >
                {
                  "Set up your Metamask wallet, load up some ETH (with additional ETH for gas). Connect your wallet, select quantity and mint. Congrats!\n"
                }
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text___0MU0
                )}
              >
                {
                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolo"
                }
              </div>

              <div
                data-plasmic-name={"rectangle18"}
                data-plasmic-override={overrides.rectangle18}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.rectangle18
                )}
              />

              <div
                data-plasmic-name={"rectangle19"}
                data-plasmic-override={overrides.rectangle19}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.rectangle19
                )}
              />

              <div
                data-plasmic-name={"rectangle20"}
                data-plasmic-override={overrides.rectangle20}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.rectangle20
                )}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__dvIy
                )}
              >
                {"Wen?"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__pVwj2
                )}
              >
                {"How many GMZillas are out there?"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__ed19
                )}
              >
                {"Wut benefits are there for GMZilla holders?"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__ogFdx
                )}
              >
                {
                  "Presale mint will begin on 22nd December at 7pm UTC (24hr window) and Public sale will begin on 23rd December at 7pm UTC."
                }
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__gdQGn
                )}
              >
                {"There are total of 10,000 GMZillas to be minted."}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__i8Elu
                )}
              >
                {
                  "Please check our jam-packed roadmap and join our discord for juicy updates."
                }
              </div>

              <div
                data-plasmic-name={"rectangle21"}
                data-plasmic-override={overrides.rectangle21}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.rectangle21
                )}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__xL8Wk
                )}
              >
                {
                  "Each NFT is generated algorithmically with more than 150 hand drawn traits with varying rarity accross categories."
                }
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text___22Juf
                )}
              >
                {"RARITY"}
              </div>

              <div
                data-plasmic-name={"group20"}
                data-plasmic-override={overrides.group20}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.group20
                )}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text___212J
                  )}
                >
                  {"Total GMZillas"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__fYOhc
                  )}
                >
                  {"10,000"}
                </div>
              </div>

              <div
                data-plasmic-name={"group21"}
                data-plasmic-override={overrides.group21}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.group21
                )}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__ji0H7
                  )}
                >
                  {"Backgrounds"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__tIeUy
                  )}
                >
                  {"Weather"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__bq3Za
                  )}
                >
                  {"Skins"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__tcWin
                  )}
                >
                  {"Outfit"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__eL3Y7
                  )}
                >
                  {"Headgear"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__cv5K0
                  )}
                >
                  {"Eyewear"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__h9DWh
                  )}
                >
                  {"Handheld"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__tSfpg
                  )}
                >
                  {"Eyes"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__bYi8I
                  )}
                >
                  {"Mouth"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__rhpeo
                  )}
                >
                  {"Plates"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text___7XdGy
                  )}
                >
                  {"22"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__aQejN
                  )}
                >
                  {"6"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__nLd5
                  )}
                >
                  {"8"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text___9JVad
                  )}
                >
                  {"10"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__h5Zal
                  )}
                >
                  {"12"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__taDhU
                  )}
                >
                  {"12"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text___4Awc
                  )}
                >
                  {"14"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text___12B4
                  )}
                >
                  {"8"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__g03W6
                  )}
                >
                  {"12"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__um7Vr
                  )}
                >
                  {"8"}
                </div>
              </div>

              <Line4Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__jrs1V
                )}
                role={"img"}
              />

              <Vector2Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__h8DPk
                )}
                role={"img"}
              />

              <Vector3Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__e7Oy
                )}
                role={"img"}
              />

              <Group3Icon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__iAUqR
                )}
                role={"img"}
              />

              <div
                data-plasmic-name={"group11"}
                data-plasmic-override={overrides.group11}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.group11
                )}
              >
                <div
                  data-plasmic-name={"layer3"}
                  data-plasmic-override={overrides.layer3}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.layer3
                  )}
                >
                  <Group6Icon
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.svg__fgU4Z
                    )}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={"group12"}
                    data-plasmic-override={overrides.group12}
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.group12
                    )}
                  >
                    <Vector5Icon
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.svg__xmNdA
                      )}
                      role={"img"}
                    />

                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___3WZes)}
                      displayHeight={"24.903px" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"100%" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"24.724px" as const}
                      loading={"lazy" as const}
                      src={{
                        src: "/plasmic/blank_project/images/group7.svg",
                        fullWidth: 24.724,
                        fullHeight: 24.903,
                        aspectRatio: 1
                      }}
                    />
                  </div>
                </div>
              </div>

              <div
                data-plasmic-name={"group27"}
                data-plasmic-override={overrides.group27}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.group27
                )}
              >
                <div
                  data-plasmic-name={"group22"}
                  data-plasmic-override={overrides.group22}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.group22
                  )}
                >
                  <div
                    data-plasmic-name={"image5"}
                    data-plasmic-override={overrides.image5}
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.image5
                    )}
                  />
                </div>

                <div
                  data-plasmic-name={"rectangle22"}
                  data-plasmic-override={overrides.rectangle22}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.rectangle22
                  )}
                />
              </div>

              <div
                data-plasmic-name={"group26"}
                data-plasmic-override={overrides.group26}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.group26
                )}
              >
                <div
                  data-plasmic-name={"group23"}
                  data-plasmic-override={overrides.group23}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.group23
                  )}
                >
                  <div
                    data-plasmic-name={"image6"}
                    data-plasmic-override={overrides.image6}
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.image6
                    )}
                  />
                </div>

                <div
                  data-plasmic-name={"rectangle23"}
                  data-plasmic-override={overrides.rectangle23}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.rectangle23
                  )}
                />
              </div>

              <div
                data-plasmic-name={"group25"}
                data-plasmic-override={overrides.group25}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.group25
                )}
              >
                <div
                  data-plasmic-name={"group24"}
                  data-plasmic-override={overrides.group24}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.group24
                  )}
                >
                  <div
                    data-plasmic-name={"image7"}
                    data-plasmic-override={overrides.image7}
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.image7
                    )}
                  />
                </div>

                <div
                  data-plasmic-name={"rectangle24"}
                  data-plasmic-override={overrides.rectangle24}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.rectangle24
                  )}
                />
              </div>
            </div>

            <div
              data-plasmic-name={"rectangle25"}
              data-plasmic-override={overrides.rectangle25}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.rectangle25
              )}
            />

            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                defaultcss.__wab_text,
                sty.text__nv1Fm
              )}
            >
              {"How do I mint?"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                defaultcss.__wab_text,
                sty.text__vVn4G
              )}
            >
              {
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam"
              }
            </div>

            <div
              data-plasmic-name={"rectangle26"}
              data-plasmic-override={overrides.rectangle26}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.rectangle26
              )}
            />

            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                defaultcss.__wab_text,
                sty.text___6VBx8
              )}
            >
              {"How do I mint?"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                defaultcss.__wab_text,
                sty.text__izi5U
              )}
            >
              {
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam"
              }
            </div>
          </div>
        </p.Stack>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "figmaPaste",
    "gmZillaLandingPage",
    "sunny1",
    "rectangle11",
    "rectangle16",
    "rectangle1",
    "frame",
    "group",
    "layer1",
    "group2",
    "rectangle3",
    "rectangle5",
    "rectangle13",
    "cherryBlossom2021",
    "rectangle6",
    "group3",
    "rectangle2",
    "group4",
    "group1",
    "preview11",
    "rectangle4",
    "rectangle7",
    "group7",
    "image4",
    "rectangle8",
    "group6",
    "image3",
    "rectangle9",
    "group5",
    "image1",
    "rectangle10",
    "group8",
    "image2",
    "rectangle12",
    "rectangle14",
    "group13",
    "group14",
    "_6011",
    "group16",
    "group17",
    "group18",
    "group19",
    "group15",
    "gmztaPreview1",
    "group9",
    "layer2",
    "group10",
    "rectangle15",
    "rectangle17",
    "setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats",
    "rectangle18",
    "rectangle19",
    "rectangle20",
    "rectangle21",
    "group20",
    "group21",
    "group11",
    "layer3",
    "group12",
    "group27",
    "group22",
    "image5",
    "rectangle22",
    "group26",
    "group23",
    "image6",
    "rectangle23",
    "group25",
    "group24",
    "image7",
    "rectangle24",
    "rectangle25",
    "rectangle26"
  ],
  figmaPaste: [
    "figmaPaste",
    "gmZillaLandingPage",
    "sunny1",
    "rectangle11",
    "rectangle16",
    "rectangle1",
    "frame",
    "group",
    "layer1",
    "group2",
    "rectangle3",
    "rectangle5",
    "rectangle13",
    "cherryBlossom2021",
    "rectangle6",
    "group3",
    "rectangle2",
    "group4",
    "group1",
    "preview11",
    "rectangle4",
    "rectangle7",
    "group7",
    "image4",
    "rectangle8",
    "group6",
    "image3",
    "rectangle9",
    "group5",
    "image1",
    "rectangle10",
    "group8",
    "image2",
    "rectangle12",
    "rectangle14",
    "group13",
    "group14",
    "_6011",
    "group16",
    "group17",
    "group18",
    "group19",
    "group15",
    "gmztaPreview1",
    "group9",
    "layer2",
    "group10",
    "rectangle15",
    "rectangle17",
    "setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats",
    "rectangle18",
    "rectangle19",
    "rectangle20",
    "rectangle21",
    "group20",
    "group21",
    "group11",
    "layer3",
    "group12",
    "group27",
    "group22",
    "image5",
    "rectangle22",
    "group26",
    "group23",
    "image6",
    "rectangle23",
    "group25",
    "group24",
    "image7",
    "rectangle24",
    "rectangle25",
    "rectangle26"
  ],
  gmZillaLandingPage: [
    "gmZillaLandingPage",
    "sunny1",
    "rectangle11",
    "rectangle16",
    "rectangle1",
    "frame",
    "group",
    "layer1",
    "group2",
    "rectangle3",
    "rectangle5",
    "rectangle13",
    "cherryBlossom2021",
    "rectangle6",
    "group3",
    "rectangle2",
    "group4",
    "group1",
    "preview11",
    "rectangle4",
    "rectangle7",
    "group7",
    "image4",
    "rectangle8",
    "group6",
    "image3",
    "rectangle9",
    "group5",
    "image1",
    "rectangle10",
    "group8",
    "image2",
    "rectangle12",
    "rectangle14",
    "group13",
    "group14",
    "_6011",
    "group16",
    "group17",
    "group18",
    "group19",
    "group15",
    "gmztaPreview1",
    "group9",
    "layer2",
    "group10",
    "rectangle15",
    "rectangle17",
    "setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats",
    "rectangle18",
    "rectangle19",
    "rectangle20",
    "rectangle21",
    "group20",
    "group21",
    "group11",
    "layer3",
    "group12",
    "group27",
    "group22",
    "image5",
    "rectangle22",
    "group26",
    "group23",
    "image6",
    "rectangle23",
    "group25",
    "group24",
    "image7",
    "rectangle24"
  ],
  sunny1: ["sunny1"],
  rectangle11: ["rectangle11"],
  rectangle16: ["rectangle16"],
  rectangle1: ["rectangle1"],
  frame: ["frame", "group", "layer1", "group2"],
  group: ["group", "layer1", "group2"],
  layer1: ["layer1", "group2"],
  group2: ["group2"],
  rectangle3: ["rectangle3"],
  rectangle5: ["rectangle5"],
  rectangle13: ["rectangle13"],
  cherryBlossom2021: ["cherryBlossom2021"],
  rectangle6: ["rectangle6"],
  group3: [
    "group3",
    "rectangle2",
    "group4",
    "group1",
    "preview11",
    "rectangle4",
    "rectangle7"
  ],
  rectangle2: ["rectangle2"],
  group4: ["group4", "group1", "preview11"],
  group1: ["group1", "preview11"],
  preview11: ["preview11"],
  rectangle4: ["rectangle4"],
  rectangle7: ["rectangle7"],
  group7: ["group7", "image4"],
  image4: ["image4"],
  rectangle8: ["rectangle8"],
  group6: ["group6", "image3"],
  image3: ["image3"],
  rectangle9: ["rectangle9"],
  group5: ["group5", "image1"],
  image1: ["image1"],
  rectangle10: ["rectangle10"],
  group8: ["group8", "image2"],
  image2: ["image2"],
  rectangle12: ["rectangle12"],
  rectangle14: ["rectangle14"],
  group13: ["group13", "group14"],
  group14: ["group14"],
  _6011: ["_6011"],
  group16: ["group16"],
  group17: ["group17"],
  group18: ["group18"],
  group19: ["group19"],
  group15: ["group15", "gmztaPreview1"],
  gmztaPreview1: ["gmztaPreview1"],
  group9: ["group9", "layer2", "group10"],
  layer2: ["layer2", "group10"],
  group10: ["group10"],
  rectangle15: ["rectangle15"],
  rectangle17: ["rectangle17"],
  setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats:
    [
      "setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats"
    ],
  rectangle18: ["rectangle18"],
  rectangle19: ["rectangle19"],
  rectangle20: ["rectangle20"],
  rectangle21: ["rectangle21"],
  group20: ["group20"],
  group21: ["group21"],
  group11: ["group11", "layer3", "group12"],
  layer3: ["layer3", "group12"],
  group12: ["group12"],
  group27: ["group27", "group22", "image5", "rectangle22"],
  group22: ["group22", "image5"],
  image5: ["image5"],
  rectangle22: ["rectangle22"],
  group26: ["group26", "group23", "image6", "rectangle23"],
  group23: ["group23", "image6"],
  image6: ["image6"],
  rectangle23: ["rectangle23"],
  group25: ["group25", "group24", "image7", "rectangle24"],
  group24: ["group24", "image7"],
  image7: ["image7"],
  rectangle24: ["rectangle24"],
  rectangle25: ["rectangle25"],
  rectangle26: ["rectangle26"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  figmaPaste: "div";
  gmZillaLandingPage: "div";
  sunny1: "div";
  rectangle11: "div";
  rectangle16: "div";
  rectangle1: "div";
  frame: "div";
  group: "div";
  layer1: "div";
  group2: "div";
  rectangle3: "div";
  rectangle5: "div";
  rectangle13: "div";
  cherryBlossom2021: "div";
  rectangle6: "div";
  group3: "div";
  rectangle2: "div";
  group4: "div";
  group1: "div";
  preview11: "div";
  rectangle4: "div";
  rectangle7: "div";
  group7: "div";
  image4: "div";
  rectangle8: "div";
  group6: "div";
  image3: "div";
  rectangle9: "div";
  group5: "div";
  image1: "div";
  rectangle10: "div";
  group8: "div";
  image2: "div";
  rectangle12: "div";
  rectangle14: "div";
  group13: "div";
  group14: "div";
  _6011: "div";
  group16: "div";
  group17: "div";
  group18: "div";
  group19: "div";
  group15: "div";
  gmztaPreview1: "div";
  group9: "div";
  layer2: "div";
  group10: "div";
  rectangle15: "div";
  rectangle17: "div";
  setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats: "div";
  rectangle18: "div";
  rectangle19: "div";
  rectangle20: "div";
  rectangle21: "div";
  group20: "div";
  group21: "div";
  group11: "div";
  layer3: "div";
  group12: "div";
  group27: "div";
  group22: "div";
  image5: "div";
  rectangle22: "div";
  group26: "div";
  group23: "div";
  image6: "div";
  rectangle23: "div";
  group25: "div";
  group24: "div";
  image7: "div";
  rectangle24: "div";
  rectangle25: "div";
  rectangle26: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicHomepage__Fetches;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    figmaPaste: makeNodeComponent("figmaPaste"),
    gmZillaLandingPage: makeNodeComponent("gmZillaLandingPage"),
    sunny1: makeNodeComponent("sunny1"),
    rectangle11: makeNodeComponent("rectangle11"),
    rectangle16: makeNodeComponent("rectangle16"),
    rectangle1: makeNodeComponent("rectangle1"),
    frame: makeNodeComponent("frame"),
    group: makeNodeComponent("group"),
    layer1: makeNodeComponent("layer1"),
    group2: makeNodeComponent("group2"),
    rectangle3: makeNodeComponent("rectangle3"),
    rectangle5: makeNodeComponent("rectangle5"),
    rectangle13: makeNodeComponent("rectangle13"),
    cherryBlossom2021: makeNodeComponent("cherryBlossom2021"),
    rectangle6: makeNodeComponent("rectangle6"),
    group3: makeNodeComponent("group3"),
    rectangle2: makeNodeComponent("rectangle2"),
    group4: makeNodeComponent("group4"),
    group1: makeNodeComponent("group1"),
    preview11: makeNodeComponent("preview11"),
    rectangle4: makeNodeComponent("rectangle4"),
    rectangle7: makeNodeComponent("rectangle7"),
    group7: makeNodeComponent("group7"),
    image4: makeNodeComponent("image4"),
    rectangle8: makeNodeComponent("rectangle8"),
    group6: makeNodeComponent("group6"),
    image3: makeNodeComponent("image3"),
    rectangle9: makeNodeComponent("rectangle9"),
    group5: makeNodeComponent("group5"),
    image1: makeNodeComponent("image1"),
    rectangle10: makeNodeComponent("rectangle10"),
    group8: makeNodeComponent("group8"),
    image2: makeNodeComponent("image2"),
    rectangle12: makeNodeComponent("rectangle12"),
    rectangle14: makeNodeComponent("rectangle14"),
    group13: makeNodeComponent("group13"),
    group14: makeNodeComponent("group14"),
    _6011: makeNodeComponent("_6011"),
    group16: makeNodeComponent("group16"),
    group17: makeNodeComponent("group17"),
    group18: makeNodeComponent("group18"),
    group19: makeNodeComponent("group19"),
    group15: makeNodeComponent("group15"),
    gmztaPreview1: makeNodeComponent("gmztaPreview1"),
    group9: makeNodeComponent("group9"),
    layer2: makeNodeComponent("layer2"),
    group10: makeNodeComponent("group10"),
    rectangle15: makeNodeComponent("rectangle15"),
    rectangle17: makeNodeComponent("rectangle17"),
    setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats:
      makeNodeComponent(
        "setUpYourMetamaskWalletLoadUpSomeEthWithAdditionalEthForGasConnectYourWalletSelectQuantityAndMintCongrats"
      ),
    rectangle18: makeNodeComponent("rectangle18"),
    rectangle19: makeNodeComponent("rectangle19"),
    rectangle20: makeNodeComponent("rectangle20"),
    rectangle21: makeNodeComponent("rectangle21"),
    group20: makeNodeComponent("group20"),
    group21: makeNodeComponent("group21"),
    group11: makeNodeComponent("group11"),
    layer3: makeNodeComponent("layer3"),
    group12: makeNodeComponent("group12"),
    group27: makeNodeComponent("group27"),
    group22: makeNodeComponent("group22"),
    image5: makeNodeComponent("image5"),
    rectangle22: makeNodeComponent("rectangle22"),
    group26: makeNodeComponent("group26"),
    group23: makeNodeComponent("group23"),
    image6: makeNodeComponent("image6"),
    rectangle23: makeNodeComponent("rectangle23"),
    group25: makeNodeComponent("group25"),
    group24: makeNodeComponent("group24"),
    image7: makeNodeComponent("image7"),
    rectangle24: makeNodeComponent("rectangle24"),
    rectangle25: makeNodeComponent("rectangle25"),
    rectangle26: makeNodeComponent("rectangle26"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
